#!/usr/bin/env bash
# A script that displays listening ports
# That shows only listening sockets
# That shows the PID and name of the program to which the socket belongs

if [ "$EUID" -ne 0 ]; then
	echo "please run as root"
	exit 1
fi

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

ss -tln | awk 'NR > 1 && $1 == "tcp" {print $1 "        " $2 "      " $3 "    " $4 "           " $6 "                     " $7}' | while read -r line; do
echo "$line"
done

ss -uln | awk 'NR > 1 && $1 == "udp" {print $1 "        " $2 "      " $3 "    " $4 "           " $6 "                                 " $7}' | while read -r line; do
echo "$line"
done

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

ss -xln | awk 'NR > 1 {print $1 "  " $2 "      [ ACC ]     " $3 "     " $4 "     " $5 "     " $6 "     " $7 "          " $8}' | while read -r line; do
echo "$line"
done
