#!/usr/bin/env bash
# A script that makes nginx listens on port 80


if ! pgrep -x "nginx" > /dev/null; then
	echo "Nginx is not running"
	exit 1
fi

ips=$(ip -4 addr show scope global | grep inet | awk '{print $2}' | cut -d '/' -f1)

for ip in $ips; do
	if ! (curl -s -m 2 "$ip:80" > /dev/null); then
		systemcrl start nginx
		exit 0
	fi
done
