#!/usr/bin/env bash
# Script that creates the file /var/run/myscript.pid,
# displays To infinity and beyond
# displays I hate the kill command when receiving a SIGTERM signal
# displays Y U no love me?! when receiving a SIGINT signal
# deletes the file /var/run/myscript.pid and terminates itself when receiving
# a SIGQUIT or SIGTERM signal

handle_signals() {
	echo "I hate the kill command"
	cleanup
}

handle_sigint() {
	echo "Y U no love me?!"
}

cleanup() {
	rm -f "/var/run/myscript.pid"
	exit 0
}

trap 'handle_signals' SIGTERM SIGQUIT
trap 'handle_sigint' SIGINT

echo "$$" > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2

done
