#!/usr/bin/env bash
# script that manages the manage_my_process script

usage() {
	echo "Usage: manage_your_process {start|stop|restart}"
	exit 1
}

if [[ $# -ne 1 ]]; then
	usage
fi

case "$1" in
	start)
		./manage_my_process &
		echo "manage_my_process started"
		;;
	stop)
		kill -TERM "$(cat /var/run/my_process.pid)"
		;;
	restart)
		kill -TERM "$(cat /var/run/my_process.pid)"
		./manage_my_process &
		echo "manage_my_process restarted"
		;;
	*)
		usage
		;;

esac
