#!/usr/bin/env bash
# Script that displays an infinite loop wtith a sleep 2 and displaying
# I am invincible!!! when receiving SIGTERM signal

handle_sigterm() {
	echo "I am invincible!!!"
	exit 0
}

trap 'handle_sigterm' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2

done
