#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd
# it also displays username, user id, Home directory path for the user


while IFS=: read -r username _ uid _ _ home _; do

	echo "Username: $username"
	echo "User ID: $uid"
	echo "Home Directory: $home"
	echo "------------------------"

done
