#!/usr/bin/env bash
# This script prints "Best School" 10 times using while but prints bad luck
# at the 4th iteration and good luck at the 8th iteration

count=1

while [ $count -le 10 ]; do

        if [ $count -eq 4 ]; then
                echo "bad luck"

	elif [ $count -eq 8 ]; then
		echo "good luck"

        else
                echo "Best School"
        fi

        ((count++))
done
