#!/usr/bin/env bash
# script that displays content of the current directory in a list format
# where only part of the name after the first dash is displayed


for filename in *; do
	echo "$filename" | cut -d '-' -f 2

done
