#!/usr/bin/env bash
# A script that configures an ubuntu server with the below requirements
# localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8

if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit 1

fi

cp /etc/hosts /etc/hosts.backup

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2 	localhost" >> /etc/hosts
echo "8.8.8.8   	facebook.com" >> /etc/hosts
